name: ğŸ“¦ Publish Schematic to GHCR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v3

      - name: ğŸ“¦ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: "@ktrdev2020"

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: ğŸ§± Build schematic
        run: npm run build

      - name: âœ… Test schematic locally
        run: |
          npm install -g @angular-devkit/schematics-cli
          schematics ./dist:crud --name=test --model="id:number,name:string"

      - name: ğŸš€ Publish to GHCR
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
